// src/App.jsx
import 'font-awesome/css/font-awesome.css'

import React from 'react'
import WebFont from 'webfontloader'
import { Container, Heading, VStack } from '@chakra-ui/react'

import ResumeContacts from './components/Contacts'
// import ResumeTimeline from './components/Timeline'

const App = () => {
  React.useEffect(() => {
    WebFont.load({
      custom: {
        families: ['Spoqa Han Sans'],
        urls: ['//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css']
      }
    })
  }, [])

  return (
    <Container maxW='xl'>
      <VStack spacing={4} align={'start'}>
        <Heading>Junyoung Park</Heading>

        <VStack spacing='4'>
          <ResumeContacts />
        </VStack>
      </VStack>
    </Container>
  )
}

export default App

// src/App.vue
<template lang="pug">
  #app: main
    section.hero.is-primary.is-bold: .hero-body: .container
      h1.title Junyoung Park

    section.section: .container: .columns
      .column.is-3
        resume-contacts
      .column.is-8.is-offset-1
        resume-timeline
</template>

<script>
import 'bulma/css/bulma.css'
import 'font-awesome/css/font-awesome.css'
import WebFont from 'webfontloader'

import ResumeContacts from './components/Contacts.vue'
import ResumeTimeline from './components/Timeline.vue'

export default {
  components: {
    ResumeContacts,
    ResumeTimeline
  },

  created () {
    WebFont.load({
      custom: {
        families: ['Spoqa Han Sans'],
        urls: ['//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css']
      }
    })
  }
}
</script>

<style>
  * {
    word-break: keep-all;
  }

  *:focus {
    outline: none;
  }

  #app {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }

  main {
    flex: 1 0 auto;
  }
</style>
